export const PERMISSIONS = {
  USER_CENTRE: 'UC-MENU-URC',
  USER: 'UC-MENU-URM',
  ORGANIZATION: 'UC-MENU-ORM',
  PERMISSION: 'UC-MENU-PNM',
  RESOURCES_FRONTEND: 'UC-MENU-RSM-FE',
  RESOURCES_BACKEND: 'UC-MENU-RSM-BE',
  ROLE: 'UC-MENU-PNREM',
  POST: 'UC-MENU-PNPS',
  SYSTEM: 'UC-MENU-SYSM'
}
